#use_frameworks!

target 'ALSTransactionSdkKit_Example' do
  pod 'ALSTransactionSdkKit', :path => '../'
  pod 'ALSPayMent'
  pod 'ALSInAppPurchase'
  target 'ALSTransactionSdkKit_Tests' do
    inherit! :search_paths

    
  end
end
